baseurl = "http://47bin.com"
languageCode = "en-us"
title = "47bin | Personal website"
paginate = 10
theme = "hyde-x"

[author]
    name = "Zubin Mehta"

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    truncate = true
    theme = "theme-base-08"
